In [1]:
# Import pandas library
import pandas as pd

# Load the data from CSV file
df = pd.read_csv('../data/raw/churn.csv')

# Show basic information
print("=== Dataset Overview ===")
print(f"Number of rows: {len(df)}")
print(f"Number of columns: {len(df.columns)}")
print("\n=== First 5 Rows ===")
display(df.head())

=== Dataset Overview ===
Number of rows: 7043
Number of columns: 21

=== First 5 Rows ===

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
# Show column names
print("=== Column Names ===")
print(df.columns.tolist())

# Show data types and missing values
print("\n=== Data Types and Missing Values ===")
print(df.info())

# Show basic statistics
print("\n=== Basic Statistics ===")
display(df.describe())

=== Column Names ===
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

=== Data Types and Missing Values ===
<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB
None

=== Basic Statistics ===

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [3]:
# Check our target variable: Churn
print("=== Churn Distribution ===")
print(df['Churn'].value_counts())
print("\n=== Churn Percentage ===")
print(df['Churn'].value_counts(normalize=True) * 100)

=== Churn Distribution ===
Churn
No     5174
Yes    1869
Name: count, dtype: int64

=== Churn Percentage ===
Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [5]:
# Check for missing values in each column
print("=== Missing Values ===")
print(df.isnull().sum())

# Check unique values in important columns
print("\n=== Unique Values in Key Columns ===")
print("Contract types:", df['Contract'].unique())
print("Payment methods:", df['PaymentMethod'].unique())
print("Internet service types:", df['InternetService'].unique())
# print("Churn values:", df['Churn'].unique())
print("Churn Values:",df['Churn'].unique())

=== Missing Values ===
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

=== Unique Values in Key Columns ===
Contract types: <StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
Payment methods: <StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
Internet service types: <StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
Churn Values: <StringArray>
['No', 'Yes']
Length: 2, dtype: str